#!/data/data/com.termux/files/usr/bin/sh
# yourTermux - Author: JubairSenseiDev - https://github.com/JubairSenseiDev/yourTermux

if [ -f "$HOME/.config/mpd/mpd.conf" ]; then 
    CONFIG="$HOME/.config/mpd/mpd.conf"; 
else 
    CONFIG="$PREFIX/etc/mpd.conf"; 
fi
exec mpd --stdout --no-daemon $CONFIG 2>&1
